---
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_POST_MAX_SIZE: "200M"
      PHP_UPLOAD_MAX_FILE_SIZE: "200M"
      AUTORUN_ENABLED: "true"
    ports:
      - "8007:8080"
    volumes:
      - .:/var/www/html/
  mysql:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
  composer:
    image: composer:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    user: "82:82"
  npm:
    image: node:current-alpine
    volumes:
      - .:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
volumes:
  db_data:
    driver: local
